EUR_SPLITBOM = [
    'EUR_SPLITBOM01',
    'EUR_SPLITBOM02',
    'EUR_SPLITBOM03',
    'EUR_SPLITBOM04',
    'EUR_SPLITBOM05',
    'EUR_SPLITBOM06',
    'EUR_SPLITBOM07',
    'EUR_SPLITBOM08',
    'EUR_SPLITBOM09',
    'EUR_SPLITBOM10',
    'EUR_SPLITBOM11',
    'EUR_SPLITBOM12',
    'EUR_SPLITBOM13',
    'EUR_SPLITBOM14',
    'EUR_SPLITBOM15',
    'EUR_SPLITBOM16',
    'EUR_SPLITBOM17',
    'EUR_SPLITBOM18',
    'EUR_SPLITBOM19',
    'EUR_SPLITBOM20',
    'EUR_SPLITBOM21',
    'EUR_SPLITBOM22',
    'EUR_SPLITBOM23',
    'EUR_SPLITBOM24',
    'EUR_SPLITBOM25',
    'EUR_SPLITBOM26',
    'EUR_SPLITBOM27',
    'EUR_SPLITBOM28',
    'EUR_SPLITBOM29',
    'EUR_SPLITBOM30',
]

LYNX_EUR_ADDERCHART = [
    'LYNX_EUR_ADDERCHART01',
    'LYNX_EUR_ADDERCHART02',
    'LYNX_EUR_ADDERCHART03',
    'LYNX_EUR_ADDERCHART04',
    'LYNX_EUR_ADDERCHART05',
    'LYNX_EUR_ADDERCHART06',
    'LYNX_EUR_ADDERCHART07',
    'LYNX_EUR_ADDERCHART08',
    'LYNX_EUR_ADDERCHART09',
    'LYNX_EUR_ADDERCHART10',
    'LYNX_EUR_ADDERCHART11',
    'LYNX_EUR_ADDERCHART12',
    'LYNX_EUR_ADDERCHART13',
    'LYNX_EUR_ADDERCHART14',
    'LYNX_EUR_ADDERCHART15',
    'LYNX_EUR_ADDERCHART16',
    'LYNX_EUR_ADDERCHART17',
    'LYNX_EUR_ADDERCHART18',
    'LYNX_EUR_ADDERCHART19',
    'LYNX_EUR_ADDERCHART20',
]

LYNX_EUR_ALLBOM = [
    'LYNX_EUR_ALLBOM01',
    'LYNX_EUR_ALLBOM13',
    'LYNX_EUR_ALLBOM14',
    'LYNX_EUR_ALLBOM15',
    'LYNX_EUR_ALLBOM16',
    'LYNX_EUR_ALLBOM17',
    'LYNX_EUR_ALLBOM18',
    'LYNX_EUR_ALLBOM19',
    'LYNX_EUR_ALLBOM20',
    'LYNX_EUR_ALLBOM21',
    'LYNX_EUR_ALLBOM22',
    'LYNX_EUR_ALLBOM23',
    'LYNX_EUR_ALLBOM24',
    'LYNX_EUR_ALLBOM25',
    'LYNX_EUR_ALLBOM26',
    'LYNX_EUR_ALLBOM27',
    'LYNX_EUR_ALLBOM28',
    'LYNX_EUR_ALLBOM29',
    'LYNX_EUR_ALLBOM30',
    'LYNX_EUR_ALLBOM31',
    'LYNX_EUR_ALLBOM32',
    'LYNX_EUR_ALLBOM33',
    'LYNX_EUR_ALLBOM34',
    'LYNX_EUR_ALLBOM35',
    'LYNX_EUR_ALLBOM36',
    'LYNX_EUR_ALLBOM37',
    'LYNX_EUR_ALLBOM38',
    'LYNX_EUR_ALLBOM39',
    'LYNX_EUR_ALLBOM40',
    'LYNX_EUR_ALLBOM41',
    'LYNX_EUR_ALLBOM42',
    'LYNX_EUR_ALLBOM43',
    'LYNX_EUR_ALLBOM44',
    'LYNX_EUR_ALLBOM45',
    'LYNX_EUR_ALLBOM46',
    'LYNX_EUR_ALLBOM47',
    'LYNX_EUR_ALLBOM48',
    'LYNX_EUR_ALLBOM49',
    'LYNX_EUR_ALLBOM50',
]

LYNX_EUR_TRACEDATA = [
    'LYNX_EUR_TRACEDATA01',
    'LYNX_EUR_TRACEDATA02',
    'LYNX_EUR_TRACEDATA03',
    'LYNX_EUR_TRACEDATA04',
    'LYNX_EUR_TRACEDATA05',
    'LYNX_EUR_TRACEDATA06',
    'LYNX_EUR_TRACEDATA07',
    'LYNX_EUR_TRACEDATA08',
    'LYNX_EUR_TRACEDATA09',
    'LYNX_EUR_TRACEDATA10',
    'LYNX_EUR_TRACEDATA11',
    'LYNX_EUR_TRACEDATA12',
    'LYNX_EUR_TRACEDATA13',
    'LYNX_EUR_TRACEDATA14',
    'LYNX_EUR_TRACEDATA15',
]

LYNX_EUR_BRD_SATMP = {
    'BDR_SectionTitle': 'BDR_SectionTitle', # инфо штам модуль и т.д.
    'BDR_Signatures': 'BDR_Signatures',  # подписи
    'BDR_TitleBlock': 'BDR_TitleBlock', # штамп
    'BDR_TitleBlock_Info': 'BDR_TitleBlock_Info', # инфо штампа
    'EUR_BDR_A1_LYNX': 'EUR_BDR_A1_LYNX', # рамка
    'EUR_BDR_GENERAL_NOTE': 'EUR_BDR_GENERAL_NOTE', # общие указания
    'LYNX_EUR_LINELIST_LINENO':'LYNX_EUR_LINELIST_LINENO', # перечень линий
    'LYNX_EUR_REFDOCS': 'LYNX_EUR_REFDOCS', # перечень ссылочных документов
    'REV_TABLE': 'REV_TABLE', # ревизии в штампе
}

LYNX_EUR_BOM_CBL_DATA = 'LYNX_EUR_BOM_CBL_DATA'
LYNX_EUR_DESIGNPARAMETERS = 'LYNX_EUR_DESIGNPARAMETERS'
LYNX_EUR_TABLEADDLINE01 = 'LYNX_EUR_TABLEADDLINE01'
LYNX_EUR_TABLEADDLINE02 = 'LYNX_EUR_TRACEADDLINE02'
